# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debate.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\033net.yairsovran.consultation'),
  serialized_pb=_b('\n\x0c\x64\x65\x62\x61te.proto\"!\n\rAnswerRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1d\n\x0b\x41nswerReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"3\n\x10\x45laborateRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08\x62lah_run\x18\x02 \x03(\x05\" \n\x0e\x45laborateReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2h\n\tCandidate\x12(\n\x06\x41nswer\x12\x0e.AnswerRequest\x1a\x0c.AnswerReply\"\x00\x12\x31\n\tElaborate\x12\x11.ElaborateRequest\x1a\x0f.ElaborateReply\"\x00\x42\x1d\n\x1bnet.yairsovran.consultationb\x06proto3')
)




_ANSWERREQUEST = _descriptor.Descriptor(
  name='AnswerRequest',
  full_name='AnswerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='AnswerRequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=49,
)


_ANSWERREPLY = _descriptor.Descriptor(
  name='AnswerReply',
  full_name='AnswerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='AnswerReply.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=80,
)


_ELABORATEREQUEST = _descriptor.Descriptor(
  name='ElaborateRequest',
  full_name='ElaborateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='ElaborateRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blah_run', full_name='ElaborateRequest.blah_run', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=133,
)


_ELABORATEREPLY = _descriptor.Descriptor(
  name='ElaborateReply',
  full_name='ElaborateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='ElaborateReply.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['AnswerRequest'] = _ANSWERREQUEST
DESCRIPTOR.message_types_by_name['AnswerReply'] = _ANSWERREPLY
DESCRIPTOR.message_types_by_name['ElaborateRequest'] = _ELABORATEREQUEST
DESCRIPTOR.message_types_by_name['ElaborateReply'] = _ELABORATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnswerRequest = _reflection.GeneratedProtocolMessageType('AnswerRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERREQUEST,
  '__module__' : 'debate_pb2'
  # @@protoc_insertion_point(class_scope:AnswerRequest)
  })
_sym_db.RegisterMessage(AnswerRequest)

AnswerReply = _reflection.GeneratedProtocolMessageType('AnswerReply', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERREPLY,
  '__module__' : 'debate_pb2'
  # @@protoc_insertion_point(class_scope:AnswerReply)
  })
_sym_db.RegisterMessage(AnswerReply)

ElaborateRequest = _reflection.GeneratedProtocolMessageType('ElaborateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ELABORATEREQUEST,
  '__module__' : 'debate_pb2'
  # @@protoc_insertion_point(class_scope:ElaborateRequest)
  })
_sym_db.RegisterMessage(ElaborateRequest)

ElaborateReply = _reflection.GeneratedProtocolMessageType('ElaborateReply', (_message.Message,), {
  'DESCRIPTOR' : _ELABORATEREPLY,
  '__module__' : 'debate_pb2'
  # @@protoc_insertion_point(class_scope:ElaborateReply)
  })
_sym_db.RegisterMessage(ElaborateReply)


DESCRIPTOR._options = None

_CANDIDATE = _descriptor.ServiceDescriptor(
  name='Candidate',
  full_name='Candidate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=169,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='Answer',
    full_name='Candidate.Answer',
    index=0,
    containing_service=None,
    input_type=_ANSWERREQUEST,
    output_type=_ANSWERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Elaborate',
    full_name='Candidate.Elaborate',
    index=1,
    containing_service=None,
    input_type=_ELABORATEREQUEST,
    output_type=_ELABORATEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CANDIDATE)

DESCRIPTOR.services_by_name['Candidate'] = _CANDIDATE

# @@protoc_insertion_point(module_scope)
